import type { ModelPricing } from '@agent-usage/shared';

export const DEFAULT_PRICING_MODELS: ModelPricing[] = [
  {
    provider: 'openai',
    model: 'gpt-4o',
    currency: 'USD',
    inputPerMillion: 2.5,
    outputPerMillion: 10,
    cachedInputPerMillion: 1.25,
    notes: 'OpenAI GPT-4o API-equivalent pricing',
  },
  {
    provider: 'openai',
    model: 'gpt-4o-mini',
    currency: 'USD',
    inputPerMillion: 0.15,
    outputPerMillion: 0.6,
    cachedInputPerMillion: 0.075,
    notes: 'OpenAI GPT-4o mini API-equivalent pricing',
  },
  {
    provider: 'openai',
    model: 'gpt-4.1',
    currency: 'USD',
    inputPerMillion: 2,
    outputPerMillion: 8,
    cachedInputPerMillion: 0.5,
    notes: 'OpenAI GPT-4.1 API-equivalent pricing',
  },
  {
    provider: 'openai',
    model: 'gpt-4.1-mini',
    currency: 'USD',
    inputPerMillion: 0.4,
    outputPerMillion: 1.6,
    cachedInputPerMillion: 0.1,
    notes: 'OpenAI GPT-4.1 mini API-equivalent pricing',
  },
  {
    provider: 'openai',
    model: 'gpt-4.1-nano',
    currency: 'USD',
    inputPerMillion: 0.1,
    outputPerMillion: 0.4,
    cachedInputPerMillion: 0.025,
    notes: 'OpenAI GPT-4.1 nano API-equivalent pricing',
  },
  {
    provider: 'openai',
    model: 'o1',
    currency: 'USD',
    inputPerMillion: 15,
    outputPerMillion: 60,
    reasoningPerMillion: 60,
    notes: 'OpenAI o1 API-equivalent pricing',
  },
  {
    provider: 'openai',
    model: 'o3',
    currency: 'USD',
    inputPerMillion: 2,
    outputPerMillion: 8,
    reasoningPerMillion: 8,
    notes: 'OpenAI o3 API-equivalent pricing',
  },
  {
    provider: 'openai',
    model: 'o3-mini',
    currency: 'USD',
    inputPerMillion: 1.1,
    outputPerMillion: 4.4,
    reasoningPerMillion: 4.4,
    notes: 'OpenAI o3 mini API-equivalent pricing',
  },
  {
    provider: 'openai',
    model: 'o4-mini',
    currency: 'USD',
    inputPerMillion: 1.1,
    outputPerMillion: 4.4,
    reasoningPerMillion: 4.4,
    notes: 'OpenAI o4 mini API-equivalent pricing',
  },
  {
    provider: 'openai',
    model: 'codex-mini-latest',
    currency: 'USD',
    inputPerMillion: 1.5,
    outputPerMillion: 6,
    cachedInputPerMillion: 0.375,
    notes: 'OpenAI Codex mini API-equivalent pricing',
  },
  {
    provider: 'anthropic',
    model: 'claude-opus-4-1-20250805',
    currency: 'USD',
    inputPerMillion: 15,
    outputPerMillion: 75,
    cachedInputPerMillion: 1.5,
    cacheWritePerMillion: 18.75,
    notes: 'Claude Opus 4.1, 5-minute prompt cache',
  },
  {
    provider: 'anthropic',
    model: 'claude-opus-4-20250514',
    currency: 'USD',
    inputPerMillion: 15,
    outputPerMillion: 75,
    cachedInputPerMillion: 1.5,
    cacheWritePerMillion: 18.75,
    notes: 'Claude Opus 4, 5-minute prompt cache',
  },
  {
    provider: 'anthropic',
    model: 'claude-sonnet-4-20250514',
    currency: 'USD',
    inputPerMillion: 3,
    outputPerMillion: 15,
    cachedInputPerMillion: 0.3,
    cacheWritePerMillion: 3.75,
    notes: 'Claude Sonnet 4, 5-minute prompt cache',
  },
  {
    provider: 'anthropic',
    model: 'claude-3-7-sonnet-20250219',
    currency: 'USD',
    inputPerMillion: 3,
    outputPerMillion: 15,
    cachedInputPerMillion: 0.3,
    cacheWritePerMillion: 3.75,
    notes: 'Claude 3.7 Sonnet, 5-minute prompt cache',
  },
  {
    provider: 'anthropic',
    model: 'claude-3-5-sonnet-20241022',
    currency: 'USD',
    inputPerMillion: 3,
    outputPerMillion: 15,
    cachedInputPerMillion: 0.3,
    cacheWritePerMillion: 3.75,
    notes: 'Claude 3.5 Sonnet, 5-minute prompt cache',
  },
  {
    provider: 'anthropic',
    model: 'claude-3-5-haiku-20241022',
    currency: 'USD',
    inputPerMillion: 0.8,
    outputPerMillion: 4,
    cachedInputPerMillion: 0.08,
    cacheWritePerMillion: 1,
    notes: 'Claude 3.5 Haiku, 5-minute prompt cache',
  },
  {
    provider: 'anthropic',
    model: 'claude-3-opus-20240229',
    currency: 'USD',
    inputPerMillion: 15,
    outputPerMillion: 75,
    cachedInputPerMillion: 1.5,
    cacheWritePerMillion: 18.75,
    notes: 'Claude 3 Opus, 5-minute prompt cache',
  },
  {
    provider: 'google',
    model: 'gemini-2.5-pro',
    currency: 'USD',
    inputPerMillion: 1.25,
    outputPerMillion: 10,
    cachedInputPerMillion: 0.125,
    notes: 'Gemini 2.5 Pro paid tier, <=200k prompt tokens',
  },
  {
    provider: 'google',
    model: 'gemini-2.5-pro-high-context',
    currency: 'USD',
    inputPerMillion: 2.5,
    outputPerMillion: 15,
    cachedInputPerMillion: 0.25,
    notes: 'Gemini 2.5 Pro paid tier, >200k prompt tokens',
  },
  {
    provider: 'google',
    model: 'gemini-2.5-flash',
    currency: 'USD',
    inputPerMillion: 0.3,
    outputPerMillion: 2.5,
    cachedInputPerMillion: 0.03,
    notes: 'Gemini 2.5 Flash standard paid tier',
  },
  {
    provider: 'google',
    model: 'gemini-2.5-flash-lite',
    currency: 'USD',
    inputPerMillion: 0.1,
    outputPerMillion: 0.4,
    cachedInputPerMillion: 0.01,
    notes: 'Gemini 2.5 Flash-Lite standard paid tier',
  },
  {
    provider: 'google',
    model: 'gemini-2.0-flash',
    currency: 'USD',
    inputPerMillion: 0.1,
    outputPerMillion: 0.4,
    cachedInputPerMillion: 0.025,
    notes: 'Gemini 2.0 Flash API-equivalent pricing',
  },
];
