import type { ModelPricing } from '@agent-usage/shared';

export const DEFAULT_PRICING_MODELS: ModelPricing[] = [
  // OpenAI flagship chat / reasoning models (standard API rates)
  {
    provider: 'openai',
    model: 'gpt-5.5',
    currency: 'USD',
    inputPerMillion: 5.0,
    outputPerMillion: 30.0,
    cachedInputPerMillion: 0.5,
    notes: 'OpenAI GPT-5.5 standard API pricing',
  },
  {
    provider: 'openai',
    model: 'gpt-5.5-pro',
    currency: 'USD',
    inputPerMillion: 30.0,
    outputPerMillion: 180.0,
    notes: 'OpenAI GPT-5.5 Pro standard API pricing',
  },
  {
    provider: 'openai',
    model: 'gpt-5.4',
    currency: 'USD',
    inputPerMillion: 2.5,
    outputPerMillion: 15.0,
    cachedInputPerMillion: 0.25,
    notes: 'OpenAI GPT-5.4 standard API pricing',
  },
  {
    provider: 'openai',
    model: 'gpt-5.4-mini',
    currency: 'USD',
    inputPerMillion: 0.75,
    outputPerMillion: 4.5,
    cachedInputPerMillion: 0.075,
    notes: 'OpenAI GPT-5.4 mini standard API pricing',
  },
  {
    provider: 'openai',
    model: 'gpt-5.4-nano',
    currency: 'USD',
    inputPerMillion: 0.2,
    outputPerMillion: 1.25,
    cachedInputPerMillion: 0.02,
    notes: 'OpenAI GPT-5.4 nano standard API pricing',
  },
  {
    provider: 'openai',
    model: 'gpt-5.4-pro',
    currency: 'USD',
    inputPerMillion: 30.0,
    outputPerMillion: 180.0,
    notes: 'OpenAI GPT-5.4 Pro standard API pricing',
  },
  {
    provider: 'openai',
    model: 'gpt-5.3-codex',
    currency: 'USD',
    inputPerMillion: 1.75,
    outputPerMillion: 14.0,
    cachedInputPerMillion: 0.175,
    notes: 'OpenAI Codex (gpt-5.3-codex) standard API pricing',
  },
  {
    provider: 'openai',
    model: 'chat-latest',
    currency: 'USD',
    inputPerMillion: 5.0,
    outputPerMillion: 30.0,
    cachedInputPerMillion: 0.5,
    notes: 'OpenAI ChatGPT chat-latest API pricing',
  },
  {
    provider: 'openai',
    model: 'computer-use-preview',
    currency: 'USD',
    inputPerMillion: 1.5,
    outputPerMillion: 6.0,
    notes: 'OpenAI computer-use-preview API pricing',
  },
  {
    provider: 'openai',
    model: 'o3-deep-research',
    currency: 'USD',
    inputPerMillion: 5.0,
    outputPerMillion: 20.0,
    notes: 'OpenAI o3 deep research standard API pricing',
  },
  {
    provider: 'openai',
    model: 'o4-mini-deep-research',
    currency: 'USD',
    inputPerMillion: 1.0,
    outputPerMillion: 4.0,
    notes: 'OpenAI o4-mini deep research standard API pricing',
  },
  // OpenAI previous-generation models
  {
    provider: 'openai',
    model: 'gpt-4o',
    currency: 'USD',
    inputPerMillion: 2.5,
    outputPerMillion: 10.0,
    cachedInputPerMillion: 1.25,
    notes: 'OpenAI GPT-4o API-equivalent pricing',
  },
  {
    provider: 'openai',
    model: 'gpt-4o-mini',
    currency: 'USD',
    inputPerMillion: 0.15,
    outputPerMillion: 0.6,
    cachedInputPerMillion: 0.075,
    notes: 'OpenAI GPT-4o mini API-equivalent pricing',
  },
  {
    provider: 'openai',
    model: 'gpt-4.1',
    currency: 'USD',
    inputPerMillion: 2.0,
    outputPerMillion: 8.0,
    cachedInputPerMillion: 0.5,
    notes: 'OpenAI GPT-4.1 API-equivalent pricing',
  },
  {
    provider: 'openai',
    model: 'gpt-4.1-mini',
    currency: 'USD',
    inputPerMillion: 0.4,
    outputPerMillion: 1.6,
    cachedInputPerMillion: 0.1,
    notes: 'OpenAI GPT-4.1 mini API-equivalent pricing',
  },
  {
    provider: 'openai',
    model: 'gpt-4.1-nano',
    currency: 'USD',
    inputPerMillion: 0.1,
    outputPerMillion: 0.4,
    cachedInputPerMillion: 0.025,
    notes: 'OpenAI GPT-4.1 nano API-equivalent pricing',
  },
  {
    provider: 'openai',
    model: 'o1',
    currency: 'USD',
    inputPerMillion: 15.0,
    outputPerMillion: 60.0,
    reasoningPerMillion: 60.0,
    notes: 'OpenAI o1 API-equivalent pricing',
  },
  {
    provider: 'openai',
    model: 'o3',
    currency: 'USD',
    inputPerMillion: 2.0,
    outputPerMillion: 8.0,
    reasoningPerMillion: 8.0,
    notes: 'OpenAI o3 API-equivalent pricing',
  },
  {
    provider: 'openai',
    model: 'o3-mini',
    currency: 'USD',
    inputPerMillion: 1.1,
    outputPerMillion: 4.4,
    reasoningPerMillion: 4.4,
    notes: 'OpenAI o3 mini API-equivalent pricing',
  },
  {
    provider: 'openai',
    model: 'o4-mini',
    currency: 'USD',
    inputPerMillion: 1.1,
    outputPerMillion: 4.4,
    reasoningPerMillion: 4.4,
    notes: 'OpenAI o4 mini API-equivalent pricing',
  },
  {
    provider: 'openai',
    model: 'codex-mini-latest',
    currency: 'USD',
    inputPerMillion: 1.5,
    outputPerMillion: 6.0,
    cachedInputPerMillion: 0.375,
    notes: 'OpenAI Codex mini API-equivalent pricing',
  },

  // Anthropic Claude current-generation models
  {
    provider: 'anthropic',
    model: 'claude-fable-5',
    currency: 'USD',
    inputPerMillion: 10.0,
    outputPerMillion: 50.0,
    cachedInputPerMillion: 1.0,
    cacheWritePerMillion: 12.5,
    notes: 'Claude Fable 5, 5-minute prompt cache',
  },
  {
    provider: 'anthropic',
    model: 'claude-mythos-5',
    currency: 'USD',
    inputPerMillion: 10.0,
    outputPerMillion: 50.0,
    cachedInputPerMillion: 1.0,
    cacheWritePerMillion: 12.5,
    notes: 'Claude Mythos 5, 5-minute prompt cache',
  },
  {
    provider: 'anthropic',
    model: 'claude-opus-4-8',
    currency: 'USD',
    inputPerMillion: 5.0,
    outputPerMillion: 25.0,
    cachedInputPerMillion: 0.5,
    cacheWritePerMillion: 6.25,
    notes: 'Claude Opus 4.8, 5-minute prompt cache',
  },
  {
    provider: 'anthropic',
    model: 'claude-opus-4-7',
    currency: 'USD',
    inputPerMillion: 5.0,
    outputPerMillion: 25.0,
    cachedInputPerMillion: 0.5,
    cacheWritePerMillion: 6.25,
    notes: 'Claude Opus 4.7, 5-minute prompt cache',
  },
  {
    provider: 'anthropic',
    model: 'claude-opus-4-6',
    currency: 'USD',
    inputPerMillion: 5.0,
    outputPerMillion: 25.0,
    cachedInputPerMillion: 0.5,
    cacheWritePerMillion: 6.25,
    notes: 'Claude Opus 4.6, 5-minute prompt cache',
  },
  {
    provider: 'anthropic',
    model: 'claude-opus-4-5',
    currency: 'USD',
    inputPerMillion: 5.0,
    outputPerMillion: 25.0,
    cachedInputPerMillion: 0.5,
    cacheWritePerMillion: 6.25,
    notes: 'Claude Opus 4.5, 5-minute prompt cache',
  },
  {
    provider: 'anthropic',
    model: 'claude-sonnet-4-6',
    currency: 'USD',
    inputPerMillion: 3.0,
    outputPerMillion: 15.0,
    cachedInputPerMillion: 0.3,
    cacheWritePerMillion: 3.75,
    notes: 'Claude Sonnet 4.6, 5-minute prompt cache',
  },
  {
    provider: 'anthropic',
    model: 'claude-sonnet-4-5',
    currency: 'USD',
    inputPerMillion: 3.0,
    outputPerMillion: 15.0,
    cachedInputPerMillion: 0.3,
    cacheWritePerMillion: 3.75,
    notes: 'Claude Sonnet 4.5, 5-minute prompt cache',
  },
  {
    provider: 'anthropic',
    model: 'claude-haiku-4-5',
    currency: 'USD',
    inputPerMillion: 1.0,
    outputPerMillion: 5.0,
    cachedInputPerMillion: 0.1,
    cacheWritePerMillion: 1.25,
    notes: 'Claude Haiku 4.5, 5-minute prompt cache',
  },
  // Anthropic Claude previous-generation models
  {
    provider: 'anthropic',
    model: 'claude-opus-4-1-20250805',
    currency: 'USD',
    inputPerMillion: 15.0,
    outputPerMillion: 75.0,
    cachedInputPerMillion: 1.5,
    cacheWritePerMillion: 18.75,
    notes: 'Claude Opus 4.1, 5-minute prompt cache',
  },
  {
    provider: 'anthropic',
    model: 'claude-opus-4-20250514',
    currency: 'USD',
    inputPerMillion: 15.0,
    outputPerMillion: 75.0,
    cachedInputPerMillion: 1.5,
    cacheWritePerMillion: 18.75,
    notes: 'Claude Opus 4, 5-minute prompt cache',
  },
  {
    provider: 'anthropic',
    model: 'claude-sonnet-4-20250514',
    currency: 'USD',
    inputPerMillion: 3.0,
    outputPerMillion: 15.0,
    cachedInputPerMillion: 0.3,
    cacheWritePerMillion: 3.75,
    notes: 'Claude Sonnet 4, 5-minute prompt cache',
  },
  {
    provider: 'anthropic',
    model: 'claude-3-7-sonnet-20250219',
    currency: 'USD',
    inputPerMillion: 3.0,
    outputPerMillion: 15.0,
    cachedInputPerMillion: 0.3,
    cacheWritePerMillion: 3.75,
    notes: 'Claude 3.7 Sonnet, 5-minute prompt cache',
  },
  {
    provider: 'anthropic',
    model: 'claude-3-5-sonnet-20241022',
    currency: 'USD',
    inputPerMillion: 3.0,
    outputPerMillion: 15.0,
    cachedInputPerMillion: 0.3,
    cacheWritePerMillion: 3.75,
    notes: 'Claude 3.5 Sonnet, 5-minute prompt cache',
  },
  {
    provider: 'anthropic',
    model: 'claude-3-5-haiku-20241022',
    currency: 'USD',
    inputPerMillion: 0.8,
    outputPerMillion: 4.0,
    cachedInputPerMillion: 0.08,
    cacheWritePerMillion: 1.0,
    notes: 'Claude 3.5 Haiku, 5-minute prompt cache',
  },
  {
    provider: 'anthropic',
    model: 'claude-3-opus-20240229',
    currency: 'USD',
    inputPerMillion: 15.0,
    outputPerMillion: 75.0,
    cachedInputPerMillion: 1.5,
    cacheWritePerMillion: 18.75,
    notes: 'Claude 3 Opus, 5-minute prompt cache',
  },

  // Google Gemini models
  {
    provider: 'google',
    model: 'gemini-2.5-pro',
    currency: 'USD',
    inputPerMillion: 1.25,
    outputPerMillion: 10.0,
    cachedInputPerMillion: 0.13,
    notes: 'Gemini 2.5 Pro paid tier, <=200k prompt tokens',
  },
  {
    provider: 'google',
    model: 'gemini-2.5-pro-high-context',
    currency: 'USD',
    inputPerMillion: 2.5,
    outputPerMillion: 15.0,
    cachedInputPerMillion: 0.25,
    notes: 'Gemini 2.5 Pro paid tier, >200k prompt tokens',
  },
  {
    provider: 'google',
    model: 'gemini-2.5-flash',
    currency: 'USD',
    inputPerMillion: 0.3,
    outputPerMillion: 2.5,
    cachedInputPerMillion: 0.03,
    notes: 'Gemini 2.5 Flash paid tier (text/image/video)',
  },
  {
    provider: 'google',
    model: 'gemini-2.5-flash-lite',
    currency: 'USD',
    inputPerMillion: 0.18,
    outputPerMillion: 0.72,
    cachedInputPerMillion: 0.02,
    notes: 'Gemini 2.5 Flash-Lite paid tier (text/image/video)',
  },
  {
    provider: 'google',
    model: 'gemini-2.0-flash',
    currency: 'USD',
    inputPerMillion: 0.1,
    outputPerMillion: 0.4,
    cachedInputPerMillion: 0.025,
    notes: 'Gemini 2.0 Flash paid tier (text/image/video)',
  },
  {
    provider: 'google',
    model: 'gemini-3.1-pro-preview',
    currency: 'USD',
    inputPerMillion: 2.0,
    outputPerMillion: 12.0,
    cachedInputPerMillion: 0.2,
    notes: 'Gemini 3.1 Pro Preview paid tier, <=200k prompt tokens',
  },
  {
    provider: 'google',
    model: 'gemini-3.1-pro-preview-high-context',
    currency: 'USD',
    inputPerMillion: 4.0,
    outputPerMillion: 18.0,
    cachedInputPerMillion: 0.4,
    notes: 'Gemini 3.1 Pro Preview paid tier, >200k prompt tokens',
  },
  {
    provider: 'google',
    model: 'gemini-3.1-flash-lite-preview',
    currency: 'USD',
    inputPerMillion: 0.1,
    outputPerMillion: 0.4,
    cachedInputPerMillion: 0.01,
    notes: 'Gemini 3.1 Flash-Lite Preview paid tier (text/image/video)',
  },
  {
    provider: 'google',
    model: 'gemini-3.5-flash',
    currency: 'USD',
    inputPerMillion: 0.75,
    outputPerMillion: 4.5,
    cachedInputPerMillion: 0.08,
    notes: 'Gemini 3.5 Flash paid tier (text/image/video)',
  },

  // Alibaba Qwen
  {
    provider: 'qwen',
    model: 'qwen-max',
    currency: 'USD',
    inputPerMillion: 2.4,
    outputPerMillion: 9.6,
    notes: 'Qwen Max API-equivalent pricing',
  },
  {
    provider: 'qwen',
    model: 'qwen-plus',
    currency: 'USD',
    inputPerMillion: 0.8,
    outputPerMillion: 2.0,
    notes: 'Qwen Plus API-equivalent pricing',
  },
  {
    provider: 'qwen',
    model: 'qwen-turbo',
    currency: 'USD',
    inputPerMillion: 0.3,
    outputPerMillion: 0.6,
    notes: 'Qwen Turbo API-equivalent pricing',
  },

  // Moonshot / Kimi
  {
    provider: 'moonshot',
    model: 'moonshot-v1-128k',
    currency: 'USD',
    inputPerMillion: 2.0,
    outputPerMillion: 8.0,
    notes: 'Moonshot/Kimi v1 128k API-equivalent pricing',
  },
];
